/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.home;

import static com.databaseCon.MotorPH_DB.con;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class ChangePassFrame extends javax.swing.JFrame {

    /**
     * Creates new form ChangePassFrame
     */
    public ChangePassFrame() {
        initComponents();
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField1Email = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jPasswordField1OldPass = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        jPasswordField1NewPass = new javax.swing.JPasswordField();
        jLabel14 = new javax.swing.JLabel();
        jPasswordField1ConPass = new javax.swing.JPasswordField();
        jButton1ForgetPass = new javax.swing.JButton();
        jButton2ChangePass = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Office Hours: 8:00AM - 5:00PM");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 670, -1, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Office Address: 5th Flr., The World Center #330 Sen. Gil Puyat Ave., Makati City, Manila, Philippines");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 690, -1, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Office Phone Number: +63-2-754-7000");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 710, -1, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Office Email: support@motorph.com");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 730, -1, 20));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Metodio Francis Oclarit");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 670, -1, 20));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Section: A1101");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 690, -1, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Subject: MO-IT101 - Computer Programming 1");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 720, -1, 20));

        jLabel10.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Change Password");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 250, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Email:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, -1, -1));
        jPanel1.add(jTextField1Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 230, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Old Password:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, -1, -1));
        jPanel1.add(jPasswordField1OldPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, 230, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("New Password:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, -1, -1));
        jPanel1.add(jPasswordField1NewPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 410, 230, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Confirm New Password:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 450, -1, -1));
        jPanel1.add(jPasswordField1ConPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 470, 230, -1));

        jButton1ForgetPass.setBackground(new java.awt.Color(0, 0, 255));
        jButton1ForgetPass.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1ForgetPass.setForeground(new java.awt.Color(255, 255, 255));
        jButton1ForgetPass.setText("Submit");
        jButton1ForgetPass.setBorderPainted(false);
        jButton1ForgetPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ForgetPassActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1ForgetPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 530, 130, -1));

        jButton2ChangePass.setBackground(new java.awt.Color(0, 0, 255));
        jButton2ChangePass.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2ChangePass.setForeground(new java.awt.Color(255, 255, 255));
        jButton2ChangePass.setText("Back");
        jButton2ChangePass.setBorderPainted(false);
        jButton2ChangePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ChangePassActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2ChangePass, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 530, 130, -1));

        jLabel1.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MotorPH");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 170, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Desktop\\mdc\\COMPUTER PROG 1\\Comp Prog Java Output\\MotorPH_MS\\src\\main\\java\\com.image\\Login.png")); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1024, 768));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1024, 768));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ForgetPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ForgetPassActionPerformed
       
         String sql=null;
        try{
                       
              sql = "select * from motorphdb where Email=?";
             PreparedStatement pst=con.prepareStatement(sql);
             String email = jTextField1Email.getText();
              pst.setString(1, email); // jtextfields name

           ResultSet rst=pst.executeQuery();
             if(rst.next()){
                    String old = rst.getString("password");
                    String oldpass = String.valueOf(jPasswordField1OldPass.getPassword());
                    String newpass = String.valueOf(jPasswordField1NewPass.getPassword());
                    String conpass = String.valueOf(jPasswordField1ConPass.getPassword());
                    if(old.equals(oldpass))
                    {
                        if (newpass.length()>3) 
                         {
                            
                           if(newpass.equals(conpass))
                           {
                            sql = "select * from motorphdb update set password='"+newpass+"' where Email='"+email+"'";
                             pst=con.prepareStatement(sql);
                             pst.execute();
                             JOptionPane.showMessageDialog(null,"password change successful");
                             this.hide();
                            MotorPH_LoginFrame loginObj = new MotorPH_LoginFrame();
                            loginObj.show();
                           }
                           else
                           {
                            JOptionPane.showMessageDialog(null,"password is not matching");
                           }
                         }
                        else
                        {
                            JOptionPane.showMessageDialog(null, "password length should be greater than 3", "Error", JOptionPane.ERROR_MESSAGE);
                        }
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null,"password is incorrect");
                    }
                }
             else{
                    JOptionPane.showMessageDialog(null,"Email does not exist");
                }
            
           
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"not possible");
        }
        
    }//GEN-LAST:event_jButton1ForgetPassActionPerformed

    private void jButton2ChangePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ChangePassActionPerformed
      this.hide();
        MotorPH_LoginFrame loginObj = new MotorPH_LoginFrame();
        loginObj.show();
    }//GEN-LAST:event_jButton2ChangePassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePassFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePassFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePassFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePassFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangePassFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1ForgetPass;
    private javax.swing.JButton jButton2ChangePass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1ConPass;
    private javax.swing.JPasswordField jPasswordField1NewPass;
    private javax.swing.JPasswordField jPasswordField1OldPass;
    private javax.swing.JTextField jTextField1Email;
    // End of variables declaration//GEN-END:variables
}
