/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.home;

import com.databaseCon.MotorPH_DB;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class MotorPH_LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form MotorPH_LoginFrame
     */
    public MotorPH_LoginFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1ForgetPass = new javax.swing.JButton();
        jButton2ChangePass = new javax.swing.JButton();
        jButton1Login = new javax.swing.JButton();
        jTextField1Email = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPasswordField1Password = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Office Hours: 8:00AM - 5:00PM");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 670, 176, 20);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Office Address: 5th Flr., The World Center #330 Sen. Gil Puyat Ave., Makati City, Manila, Philippines");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 690, 554, 20);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Office Phone Number: +63-2-754-7000");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 710, 223, 20);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Office Email: support@motorph.com");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 730, 206, 20);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Section: A1101");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(920, 690, 85, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Subject: MO-IT101 - Computer Programming 1");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(740, 720, 263, 20);

        jButton1ForgetPass.setBackground(new java.awt.Color(51, 51, 255));
        jButton1ForgetPass.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1ForgetPass.setForeground(new java.awt.Color(255, 255, 255));
        jButton1ForgetPass.setText("Forget Password");
        jButton1ForgetPass.setBorderPainted(false);
        jButton1ForgetPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ForgetPassActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1ForgetPass);
        jButton1ForgetPass.setBounds(360, 520, 140, 23);

        jButton2ChangePass.setBackground(new java.awt.Color(51, 51, 255));
        jButton2ChangePass.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2ChangePass.setForeground(new java.awt.Color(255, 255, 255));
        jButton2ChangePass.setText("Change Password");
        jButton2ChangePass.setBorderPainted(false);
        jButton2ChangePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ChangePassActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2ChangePass);
        jButton2ChangePass.setBounds(520, 520, 140, 23);

        jButton1Login.setBackground(new java.awt.Color(51, 204, 0));
        jButton1Login.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1Login.setForeground(new java.awt.Color(255, 255, 255));
        jButton1Login.setText("Login");
        jButton1Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1LoginActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1Login);
        jButton1Login.setBounds(390, 440, 230, 23);
        jPanel1.add(jTextField1Email);
        jTextField1Email.setBounds(390, 330, 230, 22);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Email:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(390, 310, 50, 20);

        jLabel10.setFont(new java.awt.Font("Lucida Calligraphy", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Welcome!");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(420, 230, 200, 50);
        jPanel1.add(jPasswordField1Password);
        jPasswordField1Password.setBounds(390, 390, 230, 22);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Password:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(390, 370, 68, 20);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Metodio Francis Oclarit");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(870, 670, 130, 20);

        jLabel1.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MotorPH");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 10, 170, 47);

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Desktop\\mdc\\COMPUTER PROG 1\\Comp Prog Java Output\\MotorPH_MS\\src\\main\\java\\com.image\\Login.png")); // NOI18N
        jPanel1.add(jLabel11);
        jLabel11.setBounds(0, 0, 1024, 768);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1024, 768));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1LoginActionPerformed
        
        String email = jTextField1Email.getText();
        String password = jPasswordField1Password.getText();
        
        Bal balObj = new Bal();
       boolean b = false;
        
        try {
            
            String query = "select Email, Password, Designation from motorphdb where Email = '"+email+"' AND Password = '"+password+"'";
            Statement st = MotorPH_DB.con.createStatement();
            ResultSet rs = st.executeQuery(query);
            if (rs.next()){
                b = true;
                   String designation = rs.getString("Designation");

            if (designation.equals("Admin")) {
                 MotorPH_HomeJFrame adminObj = new MotorPH_HomeJFrame();
                adminObj.show();
                this.hide();
            } else if (designation.equals("Employee")) {
                MotorPH_EmpFrame empObj = new MotorPH_EmpFrame();
                empObj.show();
                this.hide();
            }          
            }else {
                JOptionPane.showMessageDialog(null, "Invalid Email and Password try again.");
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, ""+e);
        }

    }//GEN-LAST:event_jButton1LoginActionPerformed

    private void jButton1ForgetPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ForgetPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ForgetPassActionPerformed

    private void jButton2ChangePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ChangePassActionPerformed
         this.hide();
        ChangePassFrame loginObj = new ChangePassFrame();
        loginObj.show();
    }//GEN-LAST:event_jButton2ChangePassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MotorPH_LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MotorPH_LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MotorPH_LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MotorPH_LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MotorPH_LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1ForgetPass;
    private javax.swing.JButton jButton1Login;
    private javax.swing.JButton jButton2ChangePass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1Password;
    private javax.swing.JTextField jTextField1Email;
    // End of variables declaration//GEN-END:variables
}
